services:
  postgres:
    container_name: activity_blog_container
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: blogger
      POSTGRES_PASSWORD: aktiVyti3_sAfe_Pass5ord
      PGDATA: /data/postgres
    ports: [ 5430:5432 ]
    networks: [ postgres ]
    restart: unless-stopped

networks:
  postgres:
    driver: bridge