version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: activity-blog-db
    environment:
      POSTGRES_USER: blogger
      POSTGRES_PASSWORD: aktiVyti3_sAfe_Pass5ord
      POSTGRES_DB: activity_blog
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
