version: '3.8'

services:
  angular-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Maps Angular app on port 80 to host port 4200
    depends_on:
      - quarkus-backend

  quarkus-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Maps Quarkus backend on port 8080
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mydb
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: blogger
      POSTGRES_PASSWORD: aktiVyti3_sAfe_Pass5ord
      POSTGRES_DB: activity_blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
