# quarkus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-backend
  template:
    metadata:
      labels:
        app: quarkus-backend
    spec:
      containers:
        - name: quarkus-backend
          image: activity-blog-backend
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/activity-blog-db
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-backend-service
spec:
  ports:
    - port: 8080
  selector:
    app: quarkus-backend
