name: Activity Blog CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Backend ---
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Quarkus backend (skip tests)
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests

      - name: Run Checkstyle
        working-directory: ./backend
        run: ./mvnw checkstyle:check

      - name: Run backend tests with coverage
        working-directory: ./backend
        run: ./mvnw test jacoco:report

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: ./backend/target/site/jacoco

      # --- Frontend ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend tests with coverage
        working-directory: ./frontend
        run: npm test -- --watchAll=false --coverage

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ./frontend/coverage

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set OWNER variable
        run: echo "OWNER=${GITHUB_ACTOR}" >> $GITHUB_ENV

      - name: Cleanup old GHCR images
        run: |
          gh api -X GET /user/packages/container/activity-blog-backend/versions \
            -H "Accept: application/vnd.github.v3+json" \
            | jq '.[].id' \
            | xargs -n 1 -I {} gh api -X DELETE /user/packages/container/activity-blog-backend/versions/{} \
              -H "Accept: application/vnd.github.v3+json" || true
          
          gh api -X GET /user/packages/container/activity-blog-frontend/versions \
            -H "Accept: application/vnd.github.v3+json" \
            | jq '.[].id' \
            | xargs -n 1 -I {} gh api -X DELETE /user/packages/container/activity-blog-frontend/versions/{} \
              -H "Accept: application/vnd.github.v3+json" || true

      - name: Build and Push Backend Docker image
        run: |
          docker build -t ghcr.io/$OWNER/activity-blog-backend:latest \
                       -t ghcr.io/$OWNER/activity-blog-backend:${{ github.sha }} ./backend
          docker push ghcr.io/$OWNER/activity-blog-backend:latest
          docker push ghcr.io/$OWNER/activity-blog-backend:${{ github.sha }}

      - name: Build and Push Frontend Docker image
        run: |
          docker build -t ghcr.io/$OWNER/activity-blog-frontend:latest \
                       -t ghcr.io/$OWNER/activity-blog-frontend:${{ github.sha }} ./frontend
          docker push ghcr.io/$OWNER/activity-blog-frontend:latest
          docker push ghcr.io/$OWNER/activity-blog-frontend:${{ github.sha }}
